[[docs]]
  name = "Getting Started"
  weight = 10
  identifier = "getting-started"
  url = "/docs/getting-started/"

[[docs]]
  name = "Development"
  weight = 11
  identifier = "development"
  url = "/docs/development/"

# [[docs]]
#   name = "Help"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

[[main]]
  name = "Documentation"
  url = "/docs/getting-started/introduction/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>"
#   url = "https://twitter.com/css_ui"
#   weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/zetareticoli/cssui"
  post = "v1.0.0"
  weight = 20

[[footer]]
  name = "Contributors"
  url = "https://github.com/zetareticoli/cssui/graphs/contributors"
  weight = 8
