# Meta Data for SEO

## Homepage
title = "CSSUI"
titleSeparator = "-"
titleAddition = "Pure CSS interactive components"
description = "CSSUI is a library of interactive components realized in pure CSS"

## Open Graph
images = ["logo-cssui.png"]
ogLocale = "en_US"
domainTLD = "cssui.dev"
titleHome = "CSSUI"

## Twitter Cards
twitterSite = "@cssui"
twitterCreator = "@zetareticoli"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "CSSUI"
schemaAuthor = "Francesco Improta"
schemaAuthorTwitter = "https://twitter.com/zetareticoli"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/francescoimprota/"
schemaAuthorGitHub = "https://github.com/zetareticoli"
schemaLocale = "en-US"
schemaLogo = "logo-cssui.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "logo-cssui.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/cssui"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/zetareticoli/cssui"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a> + <a href=\"https://gohugo.io/\">Hugo</a>"
copyRight = "Copyright (c) 2021-2021 Francesco Improta"

# Alert
alert = false
alertText = "Like CSSUI? <a class=\"alert-link\" href=\"https://github.com/zetareticoli/cssui/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/zetareticoli/cssui"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = false
  kaTex = false
  collapsibleSidebar = false
